### ISSUE TITLE
Publishing on danger.systems

### ISSUE THREAD

**Issue by Antondomashnev** [fwal/danger-jazzy#1]
Hi, good plugin, thanks for creating it 👍 
I think it deserves to be visible for all of the `danger.systems` website visitors, do you want to publish it there?

Here is a [readme](http://danger.systems/guides/creating_your_first_plugin.html#getting-it-on-danger-systems) how to do it.

**Comment by fwal** [comment]
Hi! 
Thank you for reminding me!
I made this some months ago and didn't end up using it myself and I forgot to publish it 😄 

Will fix it during the weekend, glad that you're enjoying it! 🎉

**Comment by fwal** [comment]
Sent [merge request 143](https://gitlab.com/danger-systems/danger.systems/merge_requests/143)

**Comment by Antondomashnev** [comment]
@fwal cool 🎉

**Comment by fwal** [comment]
✌️
